# ---------------------------------------------
--- # Set active profile & global defaults.
# ---------------------------------------------
spring:
  profiles:
    active: dev

  main:
    banner-mode: off

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# ---------------------------------------------
--- # Development Profile.
# ---------------------------------------------
spring:
  config:
    activate:
      on-profile: dev

<<<<<<< HEAD
  jpa:
    show-sql: true
=======
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/griffindb
    username: postgres
    password: 2102201060
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
>>>>>>> refactor_db

noclones: false
minimalclones: true

bitbucket:
  protocol: 'http://'
  apibase: '/rest/api/1.0/'
  servers:
    - '3.26.194.213'
#    - '3.26.194.213'
#gitlab:
#  protocol: 'http'
#  apibase: '/not/sure/yet/'
#  servers:
#    - '42.42.42.42'
#    - '1.2.3.4'

# ---------------------------------------------
--- # Production Profile.
# ---------------------------------------------
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create  # (create, create-drop, validate, update)

noclones: false
minimalclones: false

bitbucket:
  protocol: 'http://'
  apibase: '/rest/api/1.0/'
  servers:
    - '3.26.194.213'
