# ---------------------------------------------
--- # Set Active Profile
# ---------------------------------------------
spring:
  profiles:
    active: dev

# ---------------------------------------------
--- # Development Profile.
# ---------------------------------------------
spring:
  config:
    activate:
      on-profile: dev

  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/griffindb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

noclones: false
minimalclones: true
bitbucket:
  protocol: 'http://'
  apibase: '/rest/api/1.0/'
  servers:
    - '3.26.194.213'
    - '3.26.194.213'
gitlab:
  protocol: 'http'
  apibase: '/not/sure/yet/'
  servers:
    - '1.2.3.4'
    - '5.6.7.8'
    - '42.42.42.42'

# ---------------------------------------------
--- # Production Profile.
# ---------------------------------------------
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://localhost:5432/insightsdb  # TODO: Use a key store for this.
    username: postgres
    password: 123  # TODO: Use a key store for this.
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

noclones: false
minimalclones: false
bitbucket:
  protocol: 'http://'
  apibase: '/rest/api/1.0/'
  servers:
    - '3.26.194.213'
