---
spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/griffindb
    username: postgres
    password: 2102201060
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

noclones: false
minimalclones: true
bitbucket:
  protocol: 'http://'
  apibase: '/rest/api/1.0/'
  servers:
    - '3.26.194.213'
    - '3.26.194.213'
gitlab:
  protocol: 'http'
  apibase: '/not/sure/yet/'
  servers:
    - '1.2.3.4'
    - '5.6.7.8'
    - '42.42.42.42'
---
spring:
  config:
    activate:
      on-profile: prod
noclones: false
minimalclones: false
