---
spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  main:
    banner-mode: off
#bitbucket:
#  protocol: 'http'
#  apibase: '/rest/api/1.0/'
#  servers:
#    - '3.26.194.213'
#    - '3.26.194.213'
---
spring:
  config:
    activate:
      on-profile: prod
